services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.25
    container_name: kibana
    restart: always
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=["http://10.88.250.65:9200","http://10.88.250.66:9200","http://10.88.250.67:9200","http://10.88.250.68:9200","http://10.88.250.70:9200"]
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=Ksl@123
      - XPACK_SECURITY_ENABLED=true
    networks:
      - elastic-network

networks:
  elastic-network:
    driver: bridge
~
